// These types mirror the structure of the resume data that we expect to receive from the backend.
// The output comes from _build_resume() in resume_builder.py, which is a dictionary with the following structure:

export interface Project {
    name: string;
    date_range: string;
    collaboration: string;   // user_role.blurb from infer_user_role()
    frameworks: string[];   // top 5 imports from _get_top_frameworks()
}

export interface Language {
    name: string;
    file_count: number;
}

export interface EducationEntry {
    institution: string;
    degree: string;
    major?: string;
    minor?: string;
    date_range: string;
    notes: string;  // GPA, honours, relevant coursework, etc.
}

export interface AwardEntry {
    title: string;
    issuer: string;
    date: string;
    description: string[];  // supports bullet points
}

export interface WorkEntry {
    company: string;
    role: string;
    date_range: string;
    location?: string;
    description: string[];  // supports bullet points
}

export interface Resume {
    resume_id?: string;   // unique identifier for this resume, generated by the backend
    analysis_id: string;
    summary: string[];
    projects: Project[];
    skills: string[];   // This is for the flat list of skills from extract_metadata_skills()
    languages: Language[];
    education: EducationEntry[];
    awards: AwardEntry[];
    work_experience: WorkEntry[];

    // TODO: (for backend) we collect GitHub username and email in run_repo_analysis(), but we don't currently return it in the resume data. 
    // We should add these fields here and return them from the backend, since they are important pieces of information to display in the resume.
    github_username?: string;
    user_email?: string;
    phone?: string;
    linkedin?: string;
    full_name?: string;
}



