import { type PortfolioData } from "../types/types";
import ProjectCard from "../components/projectcard";
import LangBar from "../components/langbar";


// SAMPLE DATA 
const PORTFOLIO_DATA: PortfolioData = {
  developer: "Your Name",
  coreCompetencies: ["Mobile App Development", "Backend Development", "Web Development"],
  languages: [
    { name: "XML",          pct: 34.7, files: 50 },
    { name: "Java",         pct: 18.8, files: 27 },
    { name: "PHP",          pct: 11.8, files: 17 },
    { name: "CSS",          pct:  9.7, files: 14 },
    { name: "JavaScript",   pct:  9.0, files: 13 },
    { name: "HTML",         pct:  6.9, files: 10 },
    { name: "Kotlin",       pct:  2.1, files:  3 },
    { name: "Transact-SQL", pct:  1.4, files:  2 },
    { name: "Markdown",     pct:  0.7, files:  1 },
  ],
  projects: [
    {
      id: 1,
      name: "COSC360-project-piggybank",
      timeline: "Feb 2025 – Apr 2025",
      duration: "41 days",
      role: "Feature Developer",
      insight: "Contributed a substantial amount of new code, indicating a strong role in implementing features and expanding the project's functionality.",
      contribution: { level: "Top Contributor", teamSize: 3, rank: 1, percentile: 66.67, share: 46.0 },
      totals: { commits: 63,  files: 362, added: 11560, deleted: 3144, net: 8416 },
      mine:   { commits: 29,  added: 6523, deleted: 2096, net: 4427, files: 162 },
      technologies: [],
    },
    {
      id: 2,
      name: "341-FarmToTableApp",
      timeline: "Apr 2025 – Apr 2025",
      duration: "3 days",
      role: "Feature Developer",
      insight: "Contributed a substantial amount of new code, indicating a strong role in implementing features and expanding the project's functionality.",
      contribution: { level: "Significant Contributor", teamSize: 4, rank: 2, percentile: 50.0, share: 15.6 },
      totals: { commits: 32,  files: 326, added: 16669, deleted: 857,  net: 15812 },
      mine:   { commits: 5,   added: 836,  deleted: 16,   net: 820,  files: 26 },
      technologies: ["android.os", "java.util", "androidx.annotation"],
    },
  ],
};


export default function DevPortfolio({ data = PORTFOLIO_DATA }: { data?: PortfolioData }) {
  return (
    <div className="bg-[#0b0d10] text-[#cdd6f4] min-h-screen" style={{ fontFamily: "'DM Mono','Courier New',monospace" }}>
      <style>{CSS}</style>
      <header className="border-b border-[#1e2330] px-12 pt-14 pb-10" style={{ background: "linear-gradient(135deg,#0f1117 0%,#0b0d10 60%)" }}>
        <div className="max-w-4xl mx-auto flex items-end justify-between gap-8 flex-wrap">
          <div className="flex-1 min-w-60">
            <div className="text-[0.68rem] tracking-[0.18em] text-[#e8ff47] mb-3 uppercase">DEVELOPER PORTFOLIO</div>
            <h1 className="font-bold text-white leading-tight mb-5" style={{ fontSize: "clamp(2rem,5vw,3.5rem)", letterSpacing: "-0.03em", fontFamily: "'Syne','DM Mono',monospace" }}>{data.developer}</h1>
            <div className="flex gap-2 flex-wrap">
              {data.coreCompetencies.map(c => (
                <span key={c} className="text-[0.7rem] px-3 py-1 border border-[#2a3040] rounded-sm tracking-widest text-[#8899bb]">{c}</span>
              ))}
            </div>
          </div>
          <div className="text-right">
            <div className="font-bold text-[#e8ff47] leading-none" style={{ fontSize: "5rem", fontFamily: "'Syne',monospace" }}>{data.projects.length}</div>
            <div className="text-[0.7rem] tracking-[0.2em] text-[#556070] mt-1 uppercase">Projects</div>
          </div>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-6 py-12">
        <section className="mb-16">
          <h2 className="text-[0.72rem] tracking-[0.2em] text-[#8899bb] mb-7 flex items-center gap-3 uppercase">
            <span className="inline-block w-6 h-0.5 bg-[#e8ff47] rounded shrink-0" />
            Projects
          </h2>
          {data.projects.map((p, i) => <ProjectCard key={p.id} project={p} index={i} />)}
        </section>
        <section className="mb-16">
          <h2 className="text-[0.72rem] tracking-[0.2em] text-[#8899bb] mb-7 flex items-center gap-3 uppercase">
            <span className="inline-block w-6 h-0.5 bg-[#e8ff47] rounded shrink-0" />
            Language Proficiency
          </h2>
          <div className="bg-[#111318] border border-[#1e2330] rounded-md px-7 py-6 flex flex-col gap-3.5">
            {data.languages.map((l, i) => <LangBar key={l.name} {...l} index={i} />)}
          </div>
        </section>
      </main>
      <footer className="border-t border-[#1e2330] px-12 py-6 text-[0.65rem] text-[#334050] tracking-wide text-center">
        Generated by ImportIQ · {new Date().getFullYear()}
      </footer>
    </div>
  );
}

const CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@600;700&family=DM+Mono:wght@400;500&display=swap');
  html, body { 
    background-color: #0b0d10; 
    margin: 0; 
    padding: 0;
    min-height: 100%;
  }
  
  * { box-sizing: border-box; }
  .fade-in-card { animation: fadeUp .5s ease both; }
  @keyframes fadeUp {
    from { opacity: 0; transform: translateY(16px); }
    to   { opacity: 1; transform: translateY(0); }
  }
`;